<?php

/**
 * PluginTwitterTweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginTwitterTweet extends BaseTwitterTweet
{

  public function fromStdClass(stdClass $tweet)
  {
    $this->setTweetId($tweet->id_str);
    $this->setUserId($tweet->user->id_str);
    $this->setScreenName($tweet->user->screen_name);
    $this->setText($tweet->text);
    $this->setSource($tweet->source);
    $createdAt = new DateTime($tweet->created_at);
    $this->setCreatedAt($createdAt->format('Y-m-d H:i:s'));
  }
}