<?php
/**
 * PluginStatusUpdate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginStatusUpdate extends BaseStatusUpdate
{
  /**
   * Client names from oauth.yml to send a status update message
   * 
   * @var array
   */
  private $clients;

  /**
   * Set the client names to send a status update message
   *
   * @param array $clients
   */
  public function setClients(array $clients)
  {
    $this->clients = $clients;
  }

  /**
   * Get the client names to send a status update message
   * 
   * @return array
   */
  public function getClients()
  {
    return $this->clients;
  }

  public function postInsert($event)
  {
    $object = $event->getInvoker();
    // send and save messages for the services
    foreach ($object->getClients() as $client) {
      try {
        switch ($client) {
          case 'twitter':
            Doctrine_Core::getTable('TwitterTweet')->send($object->getMessage(), $object);
            break;
          case 'hyves':
            Doctrine_Core::getTable('HyvesWww')->send($object->getMessage(), $object);
            break;
        }
      } catch (Exception $e) {
        // @TODO move to next client and log errors
      // $client.': '.$e->getMessage();
      }
    }
  }
}