<?php

/**
 * PluginStatusUpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginStatusUpdateTable extends myDoctrineTable
{
  /**
   * Clients as defined in oauth.yml 
   * @var array
   */
  private $clients = array(
    'twitter', 
    'hyves'
  );
  
  /**
   * Cache of the available clients 
   * @var array
   */
  private $availableClients = null;

  /**
   * Returns an instance of this class.
   *
   * @return object PluginStatusUpdateTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginStatusUpdate');
  }

  /**
   * Get the clients to use for status update messages
   * 
   * @return array
   */
  public function getClients()
  {
    return $this->clients;
  }

  /**
   * Get the available clients to use for the status update messages
   * 
   * @return array
   */
  public function getAvailableClients()
  {
    if ( is_null($this->availableClients) ) {
      $result = array();
      
      foreach ($this->getClients() as $clientName) {
        $class = ucfirst($clientName);
        $client = new $class();
        if ( $client->isConnected() ) {
          $result[$clientName] = $clientName;
        }
      }
      
      $this->availableClients = $result;
    }
    
    return $this->availableClients;
  }
}