<?php

/**
 * PluginHyvesUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHyvesUserTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object PluginHyvesUserTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginHyvesUser');
  }

  public function getLoggedin()
  {
    $user = $this->findOne();
    
    if ( !$user ) {
      $client = new Hyves();
      
      if ( !$client->isConnected() ) {
        return false;
      }
      
      $response = $client->get('', array(
        'ha_method' => 'users.getLoggedin'
      ));
      $responseXml = new SimpleXMLElement($response['body']);
      
      if ( isset($responseXml->user->userid) ) {
        // create HyvesUser
        $user = new HyvesUser();
        $user->setUserid((string)$responseXml->user->userid);
        $user->setUsername((string)$responseXml->user->displayname);
        $createdAt = new DateTime();
        $createdAt->setTimestamp((int)$responseXml->user->created);
        $user->setCreatedAt($createdAt->format('Y-m-d H:i:s'));
        $user->setRaw($response['body']);
        $user->save();
      }
    }
    
    return $user;
  }
}